import {Component,useEffect,useRef,useState,type ReactNode} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Environment,Lightformer,Html,Line} from '@react-three/drei';
import {gsap} from 'gsap';
import * as THREE from 'three';
import {useTwin} from '../store';
export const strokeLength=Math.max(1,Number(import.meta.env.VITE_STROKE_LENGTH_MM)||100);
export const extension=(position:number)=>Math.max(0,Math.min(position/strokeLength,1));
export const parts=[
 {id:'end-nut',name:'End nut & washer',material:'Zinc-plated steel',purpose:'Secures the cap-end mounting.',faults:'Mechanical looseness',y:-3.45,r:.24,h:.27},
 {id:'bottom',name:'Bottom head',material:'Machined aluminium',purpose:'Closes the pressure chamber and carries the lower port.',faults:'Air Leakage, Pressure Drop',y:-3.08,r:.47,h:.48},
 {id:'port-b',name:'Cap-end air port',material:'Blue polymer / brass',purpose:'Supplies and exhausts the cap-end chamber.',faults:'Air Leakage, Valve Sticking',y:-3.08,r:.19,h:.28,port:true},
 {id:'cushion',name:'Cushion seal',material:'PU / NBR rubber',purpose:'Cushions travel near the end cap.',faults:'Seal Wear, Air Leakage',y:-2.77,r:.35,h:.15,rubber:true},
 {id:'tube',name:'Cylinder tube',material:'Brushed stainless steel',purpose:'Guides the piston and contains pressurized air.',faults:'Pressure Drop, Air Leakage',y:0,r:.405,h:5.4},
 {id:'wear',name:'Wear ring',material:'PTFE / nylon',purpose:'Guides the piston while reducing metal contact.',faults:'Seal Wear',y:-2.38,r:.34,h:.12,moving:true},
 {id:'seal',name:'Piston seal',material:'NBR / PU rubber',purpose:'Separates the two pressure chambers.',faults:'Seal Wear, Air Leakage',y:-2.23,r:.36,h:.13,rubber:true,moving:true},
 {id:'piston',name:'Piston',material:'Machined aluminium',purpose:'Converts pressure into axial force.',faults:'Seal Wear, Pressure Drop',y:-2.04,r:.35,h:.28,moving:true},
 {id:'rod',name:'Piston rod',material:'Stainless steel',purpose:'Transfers piston movement to the external load.',faults:'Valve Sticking, Seal Wear',y:.4,r:.115,h:5.0,moving:true},
 {id:'packing',name:'Rod packing',material:'NBR / PU rubber',purpose:'Maintains the dynamic rod seal.',faults:'Seal Wear, Air Leakage',y:2.76,r:.3,h:.12,rubber:true},
 {id:'wiper',name:'Rod seal / wiper',material:'PU / NBR rubber',purpose:'Excludes contamination from the rod guide.',faults:'Seal Wear',y:2.9,r:.29,h:.1,rubber:true},
 {id:'top',name:'Rod-end head',material:'Machined aluminium',purpose:'Supports the rod and closes the upper chamber.',faults:'Air Leakage, Seal Wear',y:3.07,r:.47,h:.42},
 {id:'port-a',name:'Rod-end air port',material:'Blue polymer / brass',purpose:'Supplies and exhausts the rod-end chamber.',faults:'Air Leakage, Valve Sticking',y:3.07,r:.19,h:.28,port:true},
 {id:'rod-nut',name:'Rod-end nut',material:'Zinc-plated steel',purpose:'Connects the rod to an external fixture.',faults:'Mechanical looseness',y:3.45,r:.21,h:.22,moving:true}
];
export function useReducedMotion(){const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);return reduced}
function Part({part,index,reduced}:{part:typeof parts[number];index:number;reduced:boolean}){
 const mode=useTwin(s=>s.mode),selected=useTwin(s=>s.selected),isolated=useTwin(s=>s.isolated),xray=useTwin(s=>s.xray);
 const group=useRef<THREE.Group>(null);const motion=useRef({spread:0,rod:0});const [hover,setHover]=useState(false);
 useEffect(()=>{const tween=gsap.to(motion.current,{spread:mode==='exploded'?1:0,duration:reduced?0:1.15,delay:reduced?0:index*.025,ease:'power2.inOut'});return()=>{tween.kill()}},[mode,index,reduced]);
 useFrame((_,dt)=>{const state=useTwin.getState();if(mode!=='exploded'){const target=extension(state.session?.true_simulated_state.Position??0)*2;motion.current.rod=reduced?target:THREE.MathUtils.damp(motion.current.rod,target,9,dt)}if(group.current)group.current.position.y=THREE.MathUtils.lerp(part.y+(part.moving?motion.current.rod:0),[-9,-8.4,-7.8,-7.2,-4.2,-1.25,-.9,-.5,2.4,5.15,5.55,6.15,6.8,7.4][index],motion.current.spread)});
 const dim=!!selected&&selected!==part.id;const transparent=part.id==='tube'&&(mode==='cutaway'||xray);const color=hover||selected===part.id?'#ff5a36':part.port?'#065fc9':part.rubber?'#242a2d':part.id==='wear'?'#d5d0bf':'#bbc3c6';
 return <group ref={group} visible={!isolated||selected===part.id} position={[part.port?0.48:0,part.y,part.port?0.16:0]}>
 <mesh rotation={part.port?[Math.PI/2,0,0]:[0,0,0]} onClick={e=>{e.stopPropagation();useTwin.setState({selected:part.id})}} onPointerOver={e=>{e.stopPropagation();setHover(true)}} onPointerOut={()=>setHover(false)}>
 <cylinderGeometry args={[part.r,part.r,part.h,part.id.includes('nut')?6:48,1,part.id==='tube',0,part.id==='tube'&&mode==='cutaway'?Math.PI*1.25:Math.PI*2]}/>
 <meshStandardMaterial color={color} metalness={part.rubber||part.port?0.15:.88} roughness={part.rubber?0.72:.25} transparent={transparent||dim} opacity={dim?0.16:transparent?0.18:1} side={THREE.DoubleSide}/>
 </mesh>
 {part.port&&<mesh position={[0,0,.17]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.12,.035,12,32]}/><meshStandardMaterial color="#182b3c" metalness={.7} roughness={.2}/></mesh>}
 {mode==='exploded'&&selected===part.id&&<><Line points={[[part.r,0,0],[.9,0,0]]} color="#7b8485" lineWidth={1}/><Html position={[1,0,0]} center><button className={`part-label ${selected===part.id?'selected':''}`} onClick={()=>useTwin.setState({selected:part.id})}>{String(index+1).padStart(2,'0')} / {part.name}</button></Html></>}
 </group>
}
function Flow({reduced}:{reduced:boolean}){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{const state=useTwin.getState(),s=state.session;if(!ref.current)return;ref.current.visible=!!s&&state.mode!=='exploded';if(!s)return;const confidence=s.prediction?.confidence??0;const fault=confidence>=.5?s.prediction?.fault:undefined;ref.current.children.forEach((child,i)=>{const phase=reduced?i/12:(clock.elapsedTime*.4*s.true_simulated_state.Flow/10+i/12)%1;child.position.set(.62+(fault==='Air Leakage'&&confidence>.5?phase*.5:0),-2.7+phase*5.4*s.simulation_metadata.Direction,.23);const mat=(child as THREE.Mesh).material as THREE.MeshBasicMaterial;mat.color.set(fault==='Pressure Drop'?'#ffb020':'#087f7b');mat.opacity=Math.min(.85,s.true_simulated_state.Pressure/8)* (fault==='Valve Sticking'&&!reduced?(.3+.7*Math.abs(Math.sin(clock.elapsedTime*5))):1)})});return <group ref={ref}>{Array.from({length:12},(_,i)=><mesh key={i}><sphereGeometry args={[.035,8,8]}/><meshBasicMaterial transparent opacity={.6}/></mesh>)}</group>}
function Rig({reset,reduced}:{reset:number;reduced:boolean}){const {camera,invalidate}=useThree();const mode=useTwin(s=>s.mode);useEffect(()=>{const tween=gsap.to(camera.position,{x:mode==='exploded'?10:8,y:mode==='exploded'?4:5,z:mode==='exploded'?32:15,duration:reduced?0:.9,onUpdate:()=>{camera.lookAt(0,0,0);invalidate()}});return()=>{tween.kill()}},[camera,mode,reset,reduced,invalidate]);return <OrbitControls key={reset} makeDefault target={[0,0,0]} enablePan minDistance={8} maxDistance={40} enableDamping={!reduced}/>}
class WebGLError extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="fallback">3D rendering is unavailable. Use the component index and live instruments.</div>:this.props.children}}
export default function Cylinder(){const reduced=useReducedMotion();const [reset,setReset]=useState(0);const mode=useTwin(s=>s.mode);const selected=useTwin(s=>s.selected);const part=parts.find(p=>p.id===selected);const session=useTwin(s=>s.session);return <section className="twin-stage" aria-label="Interactive pneumatic cylinder">
 <div className="stage-heading"><div><span className="eyebrow">01 / DIGITAL TWIN</span><h2>Pneumatic cylinder <span>PC-01</span></h2></div><span className="tag">{mode.toUpperCase()}</span></div>
 <div className="stage-tools"><button aria-pressed={mode==='assembled'} onClick={()=>useTwin.getState().setMode('assembled')}>Reassemble</button><button aria-pressed={mode==='cutaway'} onClick={()=>useTwin.getState().setMode('cutaway')}>Cutaway</button><button aria-pressed={useTwin(s=>s.xray)} onClick={()=>useTwin.setState(s=>({xray:!s.xray}))}>X-ray</button><button onClick={()=>setReset(n=>n+1)}>Reset camera</button></div>
 <WebGLError><Canvas dpr={[1,1.5]} camera={{position:[8,5,15],fov:38}} fallback={<div className="fallback">WebGL unavailable. Live instruments and component details remain available.</div>}><ambientLight intensity={.65}/><directionalLight position={[4,8,6]} intensity={2.5}/><Environment resolution={128}><Lightformer position={[3,0,4]} scale={[2,12,1]} intensity={4}/><Lightformer position={[-4,0,2]} scale={[2,12,1]} intensity={3}/><Lightformer position={[0,6,-4]} scale={[8,3,1]} intensity={2}/></Environment><group rotation={[0,0,-.28]}>{parts.map((p,i)=><Part key={p.id} part={p} index={i} reduced={reduced}/>)}<Flow reduced={reduced}/>{session?.prediction?.fault==='Seal Wear'&&<mesh position={[0,-2.2,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.48,.035,12,48]}/><meshBasicMaterial color="#ffb020" transparent opacity={session.prediction.confidence}/></mesh>}</group><Rig reset={reset} reduced={reduced}/></Canvas></WebGLError>
 <div className="stage-caption"><span>DRAG TO ORBIT / SCROLL TO ZOOM</span><span>{mode==='exploded'?'Conceptual component visualization':'Procedural geometry / not manufacturer CAD'}</span></div>
 <div className="stage-bottom"><div><span className="eyebrow">STROKE / SIMULATED</span><strong>{session?.true_simulated_state.Position??'-'} <small>/ {strokeLength} mm</small></strong></div><button className="primary" onClick={()=>useTwin.getState().setMode(mode==='exploded'?'assembled':'exploded')}>{mode==='exploded'?'Reassemble':'Explore Internals'} <span>{'->'}</span></button></div>
 <details className="component-index"><summary>Component index / {parts.length} assemblies</summary><div className="part-buttons">{parts.map((p,i)=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>useTwin.setState({selected:p.id})}>{String(i+1).padStart(2,'0')} {p.name}</button>)}</div></details>
 {part&&<aside className="component-detail"><button className="close" aria-label="Close component detail" onClick={()=>useTwin.setState({selected:null,isolated:false})}>X</button><span className="eyebrow">COMPONENT / CONCEPTUAL</span><h3>{part.name}</h3><p>{part.material}</p><p>{part.purpose}</p><p>Potential associations: {part.faults}. No exact damage localization is inferred.</p><button onClick={()=>useTwin.setState(s=>({isolated:!s.isolated}))}>{useTwin.getState().isolated?'Restore all':'Isolate'}</button></aside>}
 </section>}
