import {useState} from 'react';
import {AlertTriangle, CheckCircle2, Gauge, Wind} from 'lucide-react';
import {useTwin} from '../store';
import {faults, type Fault} from '../types';

type Zone = 'cap-port'|'cap-seal'|'tube'|'piston-seal'|'rod-seal'|'rod-port'|'valve';
type Guide = {zones:Zone[]; title:string; explanation:string; inspection:string; signal:string};
const guides:Record<Fault,Guide>={
 Healthy:{zones:[],title:'No fault signature detected',explanation:'Pressure, flow, speed and motion currently follow the expected simulated pattern.',inspection:'Continue normal condition monitoring.',signal:'Balanced air path'},
 'Air Leakage':{zones:['cap-port','cap-seal','piston-seal','rod-seal','rod-port'],title:'Probable air escape path',explanation:'The model sees flow and pressure behavior consistent with air leaving a sealed chamber or fitting.',inspection:'Inspect both ports, end-cap seals, piston seal and rod packing for leakage.',signal:'Unexpected flow / pressure loss'},
 'Pressure Drop':{zones:['cap-port','tube','piston-seal','rod-port','valve'],title:'Pressure is not being maintained',explanation:'Available chamber pressure is lower than expected for the simulated stroke and load.',inspection:'Check supply, regulator, valve response and internal piston sealing.',signal:'Low pressure under demand'},
 'Seal Wear':{zones:['cap-seal','piston-seal','rod-seal'],title:'Seal degradation zone',explanation:'The motion and pressure pattern points to reduced sealing between the two chambers or around the rod.',inspection:'Inspect piston seal, rod packing and end-cap cushion seals for wear or scoring.',signal:'Cross-chamber bypass / friction'},
 'Valve Sticking':{zones:['valve','cap-port','rod-port'],title:'Air switching restriction',explanation:'The cylinder response is delayed or uneven, which can occur when the directional valve does not switch freely.',inspection:'Inspect valve spool, pilot supply, exhaust silencer and both air connections.',signal:'Delayed / uneven stroke'}
};
const point:Record<Zone,[number,number]>={'valve':[72,24],'cap-port':[17,67],'cap-seal':[27,57],tube:[39,57],'piston-seal':[50,57],'rod-seal':[73,57],'rod-port':[83,42]};

export default function FaultMap(){
 const prediction=useTwin(s=>s.session?.prediction),session=useTwin(s=>s.session);const [scenario,setScenario]=useState<Fault>('Air Leakage');
 const fault=prediction?.fault??scenario,guide=guides[fault],confidence=prediction?.fault===fault?prediction.confidence:null;
 const severity=fault==='Healthy'?'normal':confidence!=null&&confidence>=.8?'high':confidence!=null&&confidence>=.5?'medium':'review';
 const pressure=session?.true_simulated_state.Pressure,flow=session?.true_simulated_state.Flow;
 return <section className={`fault-map ${fault==='Healthy'?'is-healthy':''}`} aria-label="Pneumatic fault localization map">
  <div className="fault-map-heading"><div><span className="eyebrow">FAULT LOCALIZATION / EXPLAINABLE VIEW</span><h2>{guide.title}</h2></div><div className={`severity severity-${severity}`}>{fault==='Healthy'?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} {fault==='Healthy'?'NORMAL':`${severity} ATTENTION`}</div></div>
  <div className="fault-map-layout"><div className="fault-schematic" role="img" aria-label={`${fault} schematic with ${guide.zones.length} highlighted inspection zones`}><svg viewBox="0 0 100 100" aria-hidden="true"><path className="air-line" d="M13 67H5V24H68M87 42H95V24H76"/><rect className="valve-body" x="66" y="16" width="11" height="16" rx="1"/><path className="valve-arrow" d="M69 24h5m-2-3 3 3-3 3"/><rect className="cylinder-body" x="24" y="43" width="51" height="29" rx="3"/><rect className="chamber" x="28" y="47" width="20" height="21"/><rect className="chamber" x="52" y="47" width="19" height="21"/><rect className="endcap" x="19" y="40" width="9" height="35" rx="2"/><rect className="endcap" x="71" y="40" width="8" height="35" rx="2"/><rect className="piston" x="48" y="45" width="4" height="25"/><path className="rod" d="M52 57H94"/><circle className="port" cx="18" cy="67" r="3"/><circle className="port" cx="83" cy="42" r="3"/>{guide.zones.map(zone=>{const [x,y]=point[zone];return <g className="fault-hotspot" key={zone}><circle cx={x} cy={y} r="5.5"/><circle className="hotspot-core" cx={x} cy={y} r="2.2"/></g>})}{fault==='Air Leakage'&&<g className="leak-lines"><path d="M76 54l9-5m-9 10h11m-11 5 9 5M20 60l-8-5m8 10-10 1"/></g>}{fault==='Pressure Drop'&&<path className="pressure-loss" d="M30 56h13m11 0h13"/>}{fault==='Valve Sticking'&&<path className="stuck-mark" d="M67 15l10 18m0-18-10 18"/>}</svg><div className="schematic-key"><span><i className="key-hotspot"/> Inspection zone</span><span><i className="key-air"/> Air path</span></div></div>
  <div className="fault-details"><p>{guide.explanation}</p><div className="fault-signal"><Wind size={16}/><div><span>Observed pattern</span><strong>{guide.signal}</strong></div></div><div className="fault-signal"><Gauge size={16}/><div><span>Live simulation</span><strong>{pressure!=null?`${pressure.toFixed(2)} bar · ${flow?.toFixed(2)??'—'} L/min`:'Awaiting sensor data'}</strong></div></div><div className="inspection"><span>Recommended inspection</span><strong>{guide.inspection}</strong></div>{confidence!=null&&<p className="confidence-note">AI confidence: {(confidence*100).toFixed(1)}%. Highlighted zones are inspection areas, not confirmed physical damage.</p>}</div></div>
  <div className="fault-map-footer"><span>SHOW SCENARIO</span><div role="group" aria-label="Fault visualization scenario">{faults.map(item=><button key={item} aria-pressed={fault===item} onClick={()=>setScenario(item)}>{item}</button>)}</div><small>{prediction?'Map follows the current AI diagnosis.':'Select a scenario to explore its fault signature.'}</small></div>
 </section>
}
